import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import FooterBottom from "@/layouts/footer";

const outfit = Outfit();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        {children}
        <FooterBottom/>
      </body>
    </html>
  );
}
